job_portal/employer/urls.py
from django.urls import path
from . import views

app_name = 'employer'

urlpatterns = [
    path('browseCandidates/<int:job_id>/', views.browse_candidates, name='browse_candidates'),
    path('browseCandidatesAll/', views.browse_candidates_all, name='browse_candidates_all'),
    path('view_employee_profile/', views.view_employee_profile, name='view_employee_profile'),
    path('download_employee_resume/', views.download_employee_resume, name='download_employee_resume'),
    path('addJob/', views.add_job, name='add_job'),
    path('viewJob/<int:job_id>/', views.view_job, name='view_job'),
    path('updateJob/<int:job_id>/', views.update_job, name='update_job'),
    path('profile/', views.view_employer_profile, name='view_employer_profile'),
    path('profile/create/', views.create_employer_profile, name='create_employer_profile'),
    path('profile/update/', views.update_employer_profile, name='update_employer_profile'),
    path('viewJobs/', views.view_jobs, name='view_jobs'),
    path('accept_application/<int:application_id>/', views.accept_application, name='accept_application'),
    path('reject_application/<int:application_id>/', views.reject_application, name='reject_application'),
    path('view_candidate_application/<int:applicationId>/', views.view_candidate_application, name='view_candidate_application'),
    path('export_resume_pdf/<int:candidate_id>/', views.export_resume_pdf_view, name="export_candidate_resume_pdf"),
]

job_portal/job_portal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('user.urls')),
    path('candidates/', include('candidate.urls')),
    path('employer/', include('employer.urls')),
    path('csaadmin/', include('csaadmin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

job_portal/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='clogin'),
    path('register', views.registration, name='cregister'),
    path('logout', views.logout, name='clogout')
]

job_portal/candidate/models.py
from django.db import models

from user.models import User
from employer.models import Job, Employer


class Resume(models.Model):
    summary = models.CharField(max_length=255)
    file = models.FileField(null=True, upload_to="files/")


class Education(models.Model):
    resume = models.ForeignKey(
        Resume, related_name='educations', on_delete=models.CASCADE)
    school_name = models.CharField(max_length=100)
    degree = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()


class Experience(models.Model):
    resume = models.ForeignKey(
        Resume, related_name='experiences', on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()


class Skill(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)


class Project(models.Model):
    resume = models.ForeignKey(
        Resume, related_name='projects', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()


class Candidate(models.Model):
    firstName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    resume = models.ForeignKey(
        Resume, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    savedJobs = models.ManyToManyField(Job)


class Application(models.Model):
    candidate = models.ForeignKey(
        Candidate, on_delete=models.SET_NULL, null=True, blank=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    status = models.CharField(max_length=255)


class Notification(models.Model):
    candidate = models.ForeignKey(
        Candidate, on_delete=models.SET_NULL, null=True, blank=True)
    message = models.TextField()
    read = models.BooleanField(default=False)

job_portal/employer/models.py
from django.db import models
from user.models import User


class Employer(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    companyName = models.CharField(max_length=255)
    companyEmail = models.EmailField()
    firstName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)

class Job(models.Model):
    position=models.CharField(max_length=255)
    description = models.TextField()
    applicationDeadline = models.DateField()
    status=models.CharField(max_length=255)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)

    def get_job_position(self):
        return f"{self.position}"
    
    def get_company_name(self):
        return f"{self.employer.companyName}"

job_portal/employer/forms.py
# from django.forms import ModelForm
# from .models import Resume, Job

# class JobForm(ModelForm):
#     # add more fields
#     class Meta:
#         model = Job
#         fields = ["position"]
from django import forms
from .models import Job, Employer


class JobForm(forms.ModelForm):
    STATUS_CHOICES = (
        ('OPEN', 'Open'),
        ('CLOSE', 'Close'),
    )

    class Meta:
        model = Job
        fields = ('position', 'description', 'applicationDeadline', 'status')
        widgets = {
            'position': forms.TextInput(attrs={'class': 'form-control'}),
            "description": forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Job Description'}),
            'applicationDeadline': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Job Status'  # Customize the label here
    )

    position = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Position'  # Customize the label here
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Job Description'}),
        label='Description'  # Customize the label here
    )

    applicationDeadline = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        label='Application Deadline'  # Customize the label here
    )




class EmployerForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = ('companyName', 'companyEmail', 'firstName', 'lastName', 'phone')
        widgets = {
            "firstName": forms.TextInput(attrs={'class': 'form-control'}),
            "lastName": forms.TextInput(attrs={'class': 'form-control'}),
            "companyName": forms.TextInput(attrs={'class': 'form-control'}),
            "companyEmail": forms.TextInput(attrs={'class': 'form-control'}),
            "phone": forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_companyEmail(self):
        email = self.cleaned_data.get('companyEmail')
        if not forms.EmailField().clean(email):
            raise forms.ValidationError("Invalid email format.")
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not phone.isdigit() or not (10 <= len(phone) <= 15):
            raise forms.ValidationError("Phone number must be a 10-15 digit number.")
        return phone

job_portal/employer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import FileResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from .models import User, Job, Employer
from candidate.models import Application, Notification
from .forms import JobForm, EmployerForm
from candidate.models import Candidate
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import get_template
from xhtml2pdf import pisa


def view_candidate_application(request, applicationId):
    employer = check_login(request)
    if not employer:
        return HttpResponseRedirect('/')

    application = get_object_or_404(Application, pk=applicationId)
    if application.job.employer != employer:
        return HttpResponseForbidden("You do not have permission to perform this action.")

    candidate = Candidate.objects.filter(id=application.candidate.id)[0]
    print(candidate)
    application.status = "Viewed"
    application.save()
    context = {
        'candidate': candidate,
        'application': application,
    }

    message = "Someone viewed your profile for the job: "+application.job.get_job_position()+" at "+application.job.get_company_name()
    notification = Notification(candidate=application.candidate, message=message, read=False)
    notification.save()
    
    return render(request, 'employer/view_candidate_application.html', context)

def export_resume_pdf_view(request, candidate_id):
    employer = check_login(request)
    if not employer:
        return HttpResponseRedirect('/')
    print("---------------------------")
    candidate = Candidate.objects.filter(pk=candidate_id)[0]
    template_path = 'candidates/exportResume.html'  # change to your new template path
    context = {'candidate': candidate}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="resume.pdf"'
    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
       html, dest=response, encoding='UTF-8')

    if pisa_status.err:
       return HttpResponse('We had some errors with generating your PDF <pre>' + html + '</pre>')
    return response

def accept_application(request, application_id):
    employer = check_login(request)
    if not employer:
        return HttpResponseRedirect('/')

    application = get_object_or_404(Application, pk=application_id)
    if application.job.employer != employer:
        return HttpResponseForbidden("You do not have permission to perform this action.")

    application.status = "Accepted"
    application.save()

    message = "Congratulations you are accepted for the job: "+application.job.get_job_position()+" at "+application.job.get_company_name()
    notification = Notification(candidate=application.candidate, message=message, read=False)
    notification.save()

    return HttpResponseRedirect(f'/employer/browseCandidates/{application.job.pk}')


def reject_application(request, application_id):
    employer = check_login(request)
    if not employer:
        return HttpResponseRedirect('/users/login')

    application = get_object_or_404(Application, pk=application_id)
    if application.job.employer != employer:
        return HttpResponseForbidden("You do not have permission to perform this action.")

    application.status = "Rejected"
    application.save()

    message = "Try next time for the job: "+application.job.get_job_position()+" at "+application.job.get_company_name()
    notification = Notification(candidate=application.candidate, message=message, read=False)
    notification.save()

    return HttpResponseRedirect(f'/employer/browseCandidates/{application.job.pk}')


# Check login for every request
def check_login(request):
    if 'e_id' in request.session:
        e_id = request.session['e_id']
        try:
            employer = Employer.objects.get(pk=e_id)
            return employer
        # except Exception:
        #     return HttpResponseRedirect('/users/login')
        except Employer.DoesNotExist:
            return None

    # else:
    #     return HttpResponseRedirect('/users/login')
    return None


def browse_candidates(request, job_id):
    employer = check_login(request)
    try:
        job = Job.objects.get(pk=job_id)
    except Job.DoesNotExist:
        return HttpResponseRedirect('/employer/viewJobs')

    applications = Application.objects.filter(job=job)
    candidates = [application.candidate for application in applications]

    context = {
        'job': job,
        'applications': applications
    }
    return render(request, 'employer/browse_candidates.html', context)


def browse_candidates_all(request):
    employer = check_login(request)

    # if employer is None:
    # return HttpResponseRedirect('/')

    candidates = Candidate.objects.all()

    context = {
        'candidates': candidates
    }
    return render(request, 'employer/browse_candidates_all.html', context)


# Add a job
def add_job(request):
    employer = check_login(request)

    if employer is None:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        form = JobForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.employer = employer
            job.save()
            return HttpResponseRedirect(f'/employer/viewJob/{job.id}/')
    else:
        form = JobForm()

    context = {
        'form': form,
    }
    return render(request, 'employer/add_job.html', context)

# View job details


def view_job(request, job_id):
    employer = check_login(request)
    if employer is None:
        return HttpResponseRedirect('/')
    try:
        job = Job.objects.get(pk=job_id, employer=employer)
    except Job.DoesNotExist:
        return HttpResponseRedirect('/employer/viewJobs')

    context = {
        'job': job,
    }
    return render(request, 'employer/view_job.html', context)


def update_job(request, job_id):
    employer = check_login(request)
    if employer is None:
        return HttpResponseRedirect('/')
    try:
        job = Job.objects.get(pk=job_id, employer=employer)
    except Job.DoesNotExist:
        return HttpResponseRedirect('/employer/viewJobs')

    if request.method == 'POST':
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(f'/employer/viewJob/{job.id}/')
    else:
        form = JobForm(instance=job)

    context = {
        'form': form,
        'job': job,
    }
    return render(request, 'employer/update_job.html', context)


# Employer Profile CRUD

# View and Save profile data
def create_employer_profile(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            return HttpResponseRedirect('/register')
    else:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        form = EmployerForm(request.POST)
        if form.is_valid():
            employer = form.save(commit=False)
            # employer.user = user
            # employer.save()
            # request.session["e_id"] = employer.id
            # del request.session["user_id"]
            # return HttpResponseRedirect('/employer/profile')
            if user is not None:
                employer.userID = user
                employer.save()
                request.session["e_id"] = employer.id
                del request.session["user_id"]
                return HttpResponseRedirect('/employer/profile')
    else:
        form = EmployerForm()

    context = {
        'form': form,
    }

    return render(request, 'employer/profileFormTemplate.html', context)


# Update profile
def update_employer_profile(request):
    employer = check_login(request)
    if employer is None:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        form = EmployerForm(request.POST, instance=employer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/employer/profile')
    else:
        form = EmployerForm(instance=employer)

    context = {
        'form': form,
        'employer': employer,
    }

    return render(request, 'employer/updateProfileTemplate.html', context)

# View profile


def view_employee_profile(request):
    employer = check_login(request)

    if employer is None:
        return HttpResponseRedirect('/')
    
    entry = None  # Initialize entry to None

    if request.method == 'POST':
        button_id = request.POST.get('button_id')

        try:
            entry = Candidate.objects.get(id=button_id)
        except Candidate.DoesNotExist:
            entry = None

        #print(entry.firstName)

    return render(request, 'employer/view_profile.html', context={'candidate': entry})

# View profile


def view_employer_profile(request):
    employer = check_login(request)
    if employer is None:
        return HttpResponseRedirect('/')

    return render(request, 'employer/profileTemplate.html', context={'employer': employer})


def download_employee_resume(request):
    employer = check_login(request)

    if employer is None:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        candidate_id = request.POST.get('resume_id')

        try:
            entry = Candidate.objects.get(id=candidate_id)
            obj = entry.resume
            filename = obj.file.path
            response = FileResponse(open(filename, 'rb'))
        except Candidate.DoesNotExist:
            entry = None
            response = None

    return response


# View all jobs
def view_jobs(request):
    employer = check_login(request)
    if employer is None:
        return HttpResponseRedirect('/')
    jobs = Job.objects.filter(employer=employer)

    context = {
        'jobs': jobs
    }

job_portal/templates/employer/add_job.html
{% extends "shared/base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-4">
        <div class="card-body">
          <h5 class="card-title">Add a job</h5>
          <form method="post" class="login-form" action="">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
              {% if field.errors %}
                <span class="error-message">{{ field.errors }}</span>
              {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

job_portal/templates/employer/browse_candidates.html
{% extends "shared/base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mt-4">
        <div class="card-body">
          <h5 class="card-title mb-4">List of Candidates</h5>
          <ul class="list-group">
            {% for application in applications %}
              {% csrf_token %}
              <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <h6 class="mb-0">{{ application.candidate.firstName }} {{ application.candidate.lastName }}</h6>
                    <p class="text-muted">{{ application.candidate.user.email }}</p>
                  </div>
                  <div>
                    {% if application.status == "Applied" %}
                      <span class="badge bg-warning">{{ application.status }}</span>
                    {% elif application.status == "Viewed" %}
                      <span class="badge bg-info">{{ application.status }}</span>
                    {% elif application.status == "Accepted" %}
                      <span class="badge bg-success">{{ application.status }}</span>
                    {% elif application.status == "Rejected" %}
                      <span class="badge bg-danger">{{ application.status }}</span>
                    {% endif %}
                    <span style="margin-left: 10px;"></span> <!-- Adding space here -->
                    <a href="/employer/view_candidate_application/{{ application.pk }}/" class="btn btn-outline-primary">View Profile</a>
                  </div>
                </div>
              </li>
              {% if not forloop.last %}
                <hr>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

job_portal/templates/employer/browse_candidates_all.html
{% extends "shared/base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mt-4">
        <div class="card-body">
          <h5 class="card-title mb-4">List of Candidates</h5>
          <ul class="list-group">
            <form method="post" action="{% url 'employer:view_employee_profile' %}">
                {% for candidate in candidates %}
                {% csrf_token %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <h6 class="mb-0">{{ candidate.firstName }} {{ candidate.lastName }}</h6>
                    <p class="text-muted">{{ candidate.user.email }}</p>
                </div>
                <button type="submit" class="btn btn-primary" name="button_id" value="{{ candidate.id }}">View Profile</button>                
                </li>
                {% endfor %}
            </form>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

job_portal/templates/employer/view_candidate_application.html
{% extends "shared/base.html" %}

{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">{{ candidate.firstName }} {{ candidate.lastName }}</h2>
          <p class="card-text mb-1"><strong>Phone:</strong> {{ candidate.phone }}</p>
          <p class="card-text mb-3"><strong>Email:</strong> {{ candidate.user.email }}</p>
          
          {% if candidate.resume %}
            <hr>
            <h4>Summary</h4>
            <p>{{ candidate.resume.summary }}</p>

            {% if candidate.resume.educations.all %}
              <hr>
              <h4>Education</h4>
              {% for education in candidate.resume.educations.all %}
                <div class="row mb-3">
                  <div class="col-md-9">
                    <strong>{{ education.school_name }}</strong><br>
                    <em>{{ education.degree }}</em>
                  </div>
                  <div class="col-md-3 text-md-end">
                    <span class="text-muted small">
                      {{ education.start_date|date:"F Y" }} - {{ education.end_date|date:"F Y" }}
                    </span>
                  </div>
                </div>
              
              {% endfor %}

            {% else %}
              <p>No education details available</p>
            {% endif %}
            
            {% if candidate.resume.skill_set.all %}
              <hr>
              <h4>Skills</h4>
              <ul>
                {% for skill in candidate.resume.skill_set.all %}
                  <li>{{ skill.name }}</li>
                {% endfor %}
              </ul>
            {% else %}
              <p>No skills available</p>
            {% endif %}

            {% if candidate.resume.experiences.all %}
              <hr>
              <h4>Experience</h4>
              {% for experience in candidate.resume.experiences.all %}
              <div class="row mb-3">
                <div class="col-md-9">
                  <strong>{{ experience.position }}</strong><br>
                  <em>{{ experience.company_name }}</em>
                </div>
                <div class="col-md-3 text-md-end">
                  <span class="text-muted small">
                    {{ experience.start_date|date:"F Y" }} - {{ experience.end_date|date:"F Y" }}
                  </span>
                </div>
              </div>
              <ul class="mt-0">
                {% for line in experience.description.splitlines %}
                  <li>{{ line }}</li>
                {% endfor %}
              </ul>
            {% endfor %}

            {% else %}
              <p>No experience details available</p>
            {% endif %}

            {% if candidate.resume.projects.all %}
              <hr>
              <h4>Projects</h4>
              {% for project in candidate.resume.projects.all %}
                <div class="row mb-3">
                  <div class="col-md-9">
                    <strong>{{ project.name }}</strong>
                  </div>
                  <div class="col-md-3 text-md-end">
                    <span class="text-muted small">
                      {{ project.start_date|date:"F Y" }} - {{ project.end_date|date:"F Y" }}
                    </span>
                  </div>
                </div>
                <ul class="mt-0">
                  {% for line in project.description.splitlines %}
                    <li>{{ line }}</li>
                  {% endfor %}
                </ul>
              {% endfor %}
            {% else %}
              <p>No project details available</p>
            {% endif %}
          
            
          {% else %}
            <p>No resume available</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row mt-3">
    <div class="col-md-4 mx-auto text-center">
      <div class="dropdown d-inline-block ms-md-3">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton{{ candidate.id }}" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton{{ candidate.id }}">
          <form method="post" action="{% url 'employer:download_employee_resume' %}">
            {% csrf_token %}
            {% if candidate.resume.file %}
              <button type="submit" class="dropdown-item text-primary" name="resume_id" value="{{ candidate.id }}">Download Resume</button>
            {% else %}
              <button class="dropdown-item text-primary" disabled>No Resume</button>
            {% endif %}
          </form>
          <a href="/employer/export_resume_pdf/{{ candidate.pk }}" target="_blank" class="dropdown-item text-primary">Export CSA Resume</a>
          <a href="/employer/accept_application/{{ application.pk }}" class="dropdown-item text-success">Accept</a>
          <a href="/employer/reject_application/{{ application.pk }}" class="dropdown-item text-danger">Reject</a>
        </div>
      </div>
    </div>
  </div>
  
  

{% endblock %}

job_portal/templates/employer/view_profile.html
{% extends "shared/base.html" %}

{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">{{ candidate.firstName }} {{ candidate.lastName }}</h2>
          <p class="card-text mb-1"><strong>Phone:</strong> {{ candidate.phone }}</p>
          <p class="card-text mb-3"><strong>Email:</strong> {{ candidate.user.email }}</p>
          
          {% if candidate.resume %}
            <hr>
            <h4>Summary</h4>
            <p>{{ candidate.resume.summary }}</p>

            {% if candidate.resume.educations.all %}
              <hr>
              <h4>Education</h4>
              {% for education in candidate.resume.educations.all %}
                <div class="row mb-3">
                  <div class="col-md-9">
                    <strong>{{ education.school_name }}</strong><br>
                    <em>{{ education.degree }}</em>
                  </div>
                  <div class="col-md-3 text-md-end">
                    <span class="text-muted small">
                      {{ education.start_date|date:"F Y" }} - {{ education.end_date|date:"F Y" }}
                    </span>
                  </div>
                </div>
              
              {% endfor %}

            {% else %}
              <p>No education details available</p>
            {% endif %}
            
            {% if candidate.resume.skill_set.all %}
              <hr>
              <h4>Skills</h4>
              <ul>
                {% for skill in candidate.resume.skill_set.all %}
                  <li>{{ skill.name }}</li>
                {% endfor %}
              </ul>
            {% else %}
              <p>No skills available</p>
            {% endif %}

            {% if candidate.resume.experiences.all %}
              <hr>
              <h4>Experience</h4>
              {% for experience in candidate.resume.experiences.all %}
              <div class="row mb-3">
                <div class="col-md-9">
                  <strong>{{ experience.position }}</strong><br>
                  <em>{{ experience.company_name }}</em>
                </div>
                <div class="col-md-3 text-md-end">
                  <span class="text-muted small">
                    {{ experience.start_date|date:"F Y" }} - {{ experience.end_date|date:"F Y" }}
                  </span>
                </div>
              </div>
              <ul class="mt-0">
                {% for line in experience.description.splitlines %}
                  <li>{{ line }}</li>
                {% endfor %}
              </ul>
            {% endfor %}

            {% else %}
              <p>No experience details available</p>
            {% endif %}

            {% if candidate.resume.projects.all %}
              <hr>
              <h4>Projects</h4>
              {% for project in candidate.resume.projects.all %}
                <div class="row mb-3">
                  <div class="col-md-9">
                    <strong>{{ project.name }}</strong>
                  </div>
                  <div class="col-md-3 text-md-end">
                    <span class="text-muted small">
                      {{ project.start_date|date:"F Y" }} - {{ project.end_date|date:"F Y" }}
                    </span>
                  </div>
                </div>
                <ul class="mt-0">
                  {% for line in project.description.splitlines %}
                    <li>{{ line }}</li>
                  {% endfor %}
                </ul>
              {% endfor %}
            {% else %}
              <p>No project details available</p>
            {% endif %}
          
            
          {% else %}
            <p>No resume available</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
<div class="mt-3 text-center d-flex justify-content-center">
  <form method="post" action="{% url 'employer:download_employee_resume' %}" class="me-3">
    {% csrf_token %}
  {% if candidate.resume.file %}
    <button type="submit" class="btn btn-primary" name="resume_id" value="{{ candidate.id }}">Download Resume</button>
  {% else %}
    <button class="btn btn-primary" disabled>No Resume</button>
  {% endif %}
  </form>
  <a href="/employer/export_resume_pdf/{{ candidate.pk }}" target="_blank" class="btn btn-primary">Export CSA Resume</a>
</div>
{% endblock %}